apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
      - name: pizza-pod
        image: amouat/pizza:today
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-svc
spec:
  selector:
    app: pizza
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
